combine overrides logs
arup-group/mc pull request #49
Opened 2022-03-29 16:29 UTC by syhwawa

Some works followed by the [PR adds overrides log#48](https://github.com/arup-group/mc/pull/48).

Add functions that find all of `matsim_overrides.log` from various simulations submitted via the bitsim batch file and merge all of the logs at 0 iterations into a `matsim_overrides_summary`. The summary override log is saved in the simulation root directory. 

Examples should like: 
```
----------------------------------------------------------------------------------------------------
log_path:/mnt/efs/simulation_name1/0/matsim_overrides.log
flowCapacityFactor: 1 -> 0.01
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
----------------------------------------------------------------------------------------------------
log_path:/mnt/efs/simulation_name2/0/matsim_overrides.log
flowCapacityFactor: 1 -> 0.02
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
```
Will test it in bitsim.

2022-03-30 08:00 UTC, rorysedgwick commented
Before looking at the actual content of this PR, i'd make the same comment about squashing the commit history :) if you haven't worked with `rebase` before or don't feel comfortable doing that i'd be happy to go through it with you. That's also still just my preference, and not something that's a hard requirement.

It also looks like there's some conflicts in the tests - I don't think you've got Fred's latest changes in your branch, which should be merged/resolved before this PR.

2022-03-30 10:36 UTC, fredshone requested changes
I like the attempt. However - in the case of a swarm - is `root` the root of the swarm? I think it is the root of the individual simulation within the swarm, so that this summary will get written to the root of each individual simulation and will only summaries that single simulation? I think this is fine but might be simpler to add the logic directly to autostep, ie:

```
if first_iteration():
    write_override_log(root)
```

To get a log summarising an entire swarm (which would be v useful), ideally @rorysedgwick creates a task within the orchestration that sits "outside" all the individual swarm simulations. I think this is in progress.

I think the way you have written this will be quite robust to missing data, ie it won't fail if a path is missing, which is great - we must remeber to do this for all logs and summaries. So that we don't get crashing swarms because of simple log errors.

2022-03-30 10:36 UTC, fredshone commented on mc/autostep.py
> +    file_name = 'matsim_overrides.org'
`.org` ?

2022-03-30 10:36 UTC, fredshone commented on mc/summarise.py
> +def find_log_file(file_name, root_dir):
rename find_log_file`s`.

otherwise nice

2022-03-30 10:36 UTC, fredshone commented on mc/summarise.py
> +    file_diretory = []
dire`c`tory

2022-03-31 13:39 UTC, syhwawa commented
> Before looking at the actual content of this PR, i'd make the same comment about squashing the commit history :) if you haven't worked with `rebase` before or don't feel comfortable doing that i'd be happy to go through it with you. That's also still just my preference, and not something that's a hard requirement.


Thanks for the comments. I have googled the `rebase` since you mentioned it in the previous PR and will try to merge all the commits together when I pushed the next commit. 
> 
> It also looks like there's some conflicts in the tests - I don't think you've got Fred's latest changes in your branch, which should be merged/resolved before this PR.

Yeah. I will pull the latest changes and make some modifications based on that.

2022-04-01 09:16 UTC, syhwawa commented on mc/autostep.py
> +    file_name = 'matsim_overrides.org'
I used `endswith` to find the files. I have removed the `.org` by using `startswith`

2022-04-01 09:16 UTC, syhwawa commented on mc/autostep.py
> +    file_name = 'matsim_overrides.org'
I used `endswith` to find the files. I have removed the `.org` by using `startswith`

2022-04-01 09:28 UTC, syhwawa commented
Thanks for the comments! @fredshone

I have changed the sim_root to the simulation_root_directory and only called `summarise_overrides_log` in the first iteration. 

I have tested on bitsim and the combined overrides log did write the file in the right simulation root directory. 

The combined log looks like:
```
----------------------------------------------------------------------------------------------------
log_path:/efs/Londinium/simulations_output/20220329_log_test/baseline_1pct/0/matsim_overrides.log
flowCapacityFactor: 1 -> 0.01
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
----------------------------------------------------------------------------------------------------
log_path:/efs/Londinium/simulations_output/20220329_log_test/baseline_2pct/0/matsim_overrides.log
flowCapacityFactor: 1 -> 0.02
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/constant: 0.0 -> -50
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
modeParams:car/monetaryDistanceRate: -0.0005 -> -0.000289
```

2022-04-04 09:10 UTC, fredshone commented
In your example output you show a combined summary from two different "runs": 
> log_path:/efs/Londinium/simulations_output/20220329_log_test/baseline_1pct/0/matsim_overrides.log
> log_path:/efs/Londinium/simulations_output/20220329_log_test/baseline_2pct/0/matsim_overrides.log
...is this correct? My reading of the code is that it would only find a single simulation run when accessing `root`.

2022-04-04 09:25 UTC, syhwawa commented
> In your example output you show a combined summary from two different "runs":
> 
> > log_path:/efs/Londinium/simulations_output/20220329_log_test/baseline_1pct/0/matsim_overrides.log
> > log_path:/efs/Londinium/simulations_output/20220329_log_test/baseline_2pct/0/matsim_overrides.log
> 
> ...is this correct? My reading of the code is that it would only find a single simulation run when accessing `root`.

I think yes since we are aiming to combine the different logs from various "runs". I have changed the root to each "run" the parent simulation root directory. 
```
    simulation_root_dir = sim_root.parent
    if first_iteration:
        summarise_overrides_log(file_name, simulation_root_dir)
```
And it will go through each simulation folder to find the overrides log. 
```
def find_log_files(file_name, root_dir):
    """
    Find the path for log files for the jobs from different simulation jobs
    """
    file_directory = []
    for root, dirs, files in os.walk(root_dir):
        for file in files:
            if file.startswith(file_name):
                if str(root)[-2:] == '/0':  # find the file in zero iteration only in the simulation folder
                    file_directory.append(os.path.join(root, file))
    return file_directory
```

2022-04-04 09:47 UTC, fredshone commented
thanks, I didn't spot that, however, if this is run as a regular bitsim run without the swarm (ie without a "batch" config) - it will summarise everything it find in root.

I think remove this requirement to combine multiple runs until there is an obvious place to put it.

I will suggest changes.

2022-04-04 10:32 UTC, syhwawa commented
> thanks, I didn't spot that, however, if this is run as a regular bitsim run without the swarm (ie without a "batch" config) - it will summarise everything it find in root.
> 
> I think remove this requirement to combine multiple runs until there is an obvious place to put it.
> 
> I will suggest changes

Thanks. You are right. It will combine all of the overrides logs from every folder in the root in the 0 iteration. It could still be useful as a lookup log when we submitted several experimental simulations from various batch jobs or without job config at different time. 

I have some experience running several different swarm simulations based on getting the feedback from previous experimental simulations for calibration purpose. Since all of these simulations are saved into the same root directory, I believed these simulations should belong to similar experimental jobs that we would like to compare. 

Happy to hold this combined override log and implement it when we have a "conductor" job.

>As it is the override log writes to sim_root/0/, but you might prefer it to write to sim_root/? Feel free to change

`sim_root/0/` is good for me to keep the single override log for each simulation.

2022-04-04 20:49 UTC, syhwawa commented
> > I have some experience running several different swarm simulations based on getting the feedback from previous experimental simulations for calibration purpose. Since all of these simulations are saved into the same root directory, I believed these simulations should belong to similar experimental jobs that we would like to compare.
> 
> makes sense - if useful to you then keep it in 👍🏻

I reverted the previous commit and merged them together. I will keep the combined log for now and I am happy to shift it to the bitsim when the swarm conductor is ready in the bitsim step function😃 . @fredshone

2022-04-05 09:47 UTC, fredshone approved these changes

2022-04-05 10:28 UTC, syhwawa commented on mc/autostep.py
> +    if prev_iteration == 0:
Modified it to `prev_iteration` which should be correct now. @fredshone

2022-04-05 10:37 UTC, syhwawa commented on mc/autostep.py
> +    if first_iteration:
MATSim 2 & RUST 🚀 
https://media.giphy.com/media/H6LqIBAojMWQw8oCU5/giphy.gif

2022-04-06 15:46 UTC, merged